# Site
name: "bbhmsitename"
title: "learning - jkl"
description: "descirbe it for GA"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
google_analytics: 'G-XXXXXXXXX'
disqus: 'demowebsite'
#mailchimp-list: ''
include: [ "_pages", "_posts" ]
permalink: /:title/
email: my_email@domaine.com

# data date
local:
  date:
    months:
      - Janvier
      - Février
      - Mars
      - Avril
      - Mai
      - Juin
      - Juillet
      - Aout
      - Septembre
      - Octobre
      - Novembre
      - Décembre

# Authors
authors:
  bbhm:
    name: bbhm
    display_name: bbhm
    avatar: 'assets/images/me.jpg'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: my_email@domaine.com
    web: https://bbhm.000webhostapp.com/
    twitter: https://twitter.com/bbhm
    description: "En vacances"


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-redirect-from

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 5
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: false



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed


  # Exclude from processing.
  # The following items will not be processed, by default.
  # Any item listed under the `exclude:` key here will be automatically added to
  # the internal "default list".
  #
  # Excluded items can be processed by explicitly listing the directories or
  # their entries' file path in the `include:` list.
  #
  # exclude:
  #  - .sass-cache/
  #   - .jekyll-cache/
  #   - gemfiles/
  #   - Gemfile
  #   - Gemfile.lock
  #- node_modules/
  #   - vendor/bundle/
  #   - vendor/cache/
  #   - vendor/gems/
  #   - vendor/ruby/

exclude: [
  changelog.md,
  LICENSE.txt,
  README.md,
  Gemfile,
  Gemfile.lock,
  .sass-cache/,
  .jekyll-cache/,
  "*.pdf",
  treegenerate.md,
  "*.js",
  gitbook_recquierment/,
]


# replace this theme by an other
theme : just-the-docs
