db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: dev2020laravel
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: dev
    MYSQL_ROOT_PASSWORD: dev2020laravel